"""drop redundant tenant_id indexes

Revision ID: 9dfcd3c93c6f
Revises: c41a6a43cc99
Create Date: 2026-07-10 17:26:17.526865

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dfcd3c93c6f'
down_revision: str | None = 'c41a6a43cc99'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negotiation_cases', schema=None) as batch_op:
        batch_op.drop_index('ix_negotiation_cases_tenant_id')

    with op.batch_alter_table('negotiation_results', schema=None) as batch_op:
        batch_op.drop_index('ix_negotiation_results_tenant_id')

    with op.batch_alter_table('product_specs', schema=None) as batch_op:
        batch_op.drop_index('ix_product_specs_tenant_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_tenant_id')

    with op.batch_alter_table('strategy_sheets', schema=None) as batch_op:
        batch_op.drop_index('ix_strategy_sheets_tenant_id')

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index('ix_suppliers_tenant_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index('ix_suppliers_tenant_id', ['tenant_id'], unique=False)

    with op.batch_alter_table('strategy_sheets', schema=None) as batch_op:
        batch_op.create_index('ix_strategy_sheets_tenant_id', ['tenant_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_tenant_id', ['tenant_id'], unique=False)

    with op.batch_alter_table('product_specs', schema=None) as batch_op:
        batch_op.create_index('ix_product_specs_tenant_id', ['tenant_id'], unique=False)

    with op.batch_alter_table('negotiation_results', schema=None) as batch_op:
        batch_op.create_index('ix_negotiation_results_tenant_id', ['tenant_id'], unique=False)

    with op.batch_alter_table('negotiation_cases', schema=None) as batch_op:
        batch_op.create_index('ix_negotiation_cases_tenant_id', ['tenant_id'], unique=False)

    # ### end Alembic commands ###
