"""initial schema (13 tables)

Revision ID: c41a6a43cc99
Revises: 
Create Date: 2026-07-10 17:06:46.215452

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41a6a43cc99'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infomart_categories',
    sa.Column('infomart_code', sa.String(length=6), nullable=False),
    sa.Column('category_l1', sa.Text(), nullable=True),
    sa.Column('category_l2', sa.Text(), nullable=True),
    sa.Column('category_l3', sa.Text(), nullable=True),
    sa.Column('category_l4', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('infomart_code')
    )
    op.create_table('model_versions',
    sa.Column('model_version_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('model_type', sa.String(length=16), nullable=False),
    sa.Column('version_label', sa.String(length=20), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('model_version_id'),
    sa.UniqueConstraint('tenant_id', 'model_type', 'version_label', name='uq_model_versions_key')
    )
    op.create_table('products',
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('tenant_id', 'product_id', name='uq_products_tenant_id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('rate_change_reasons',
    sa.Column('reason_id', sa.String(length=8), nullable=False),
    sa.Column('reason_name', sa.Text(), nullable=False),
    sa.Column('impact_direction', sa.String(length=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('reason_id')
    )
    op.create_table('raw_imports',
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('import_batch_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('normalize_status', sa.String(length=16), nullable=False),
    sa.Column('normalize_error', sa.Text(), nullable=True),
    sa.Column('target_table', sa.String(length=64), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('normalized_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('import_id')
    )
    with op.batch_alter_table('raw_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_imports_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_imports_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('suppliers',
    sa.Column('supplier_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_name', sa.Text(), nullable=False),
    sa.Column('supplier_category', sa.Text(), nullable=True),
    sa.Column('supplier_memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('supplier_id'),
    sa.UniqueConstraint('tenant_id', 'supplier_id', name='uq_suppliers_tenant_id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenants',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_name', sa.Text(), nullable=False),
    sa.Column('case_no_prefix', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('product_specs',
    sa.Column('spec_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('part', sa.Text(), nullable=True),
    sa.Column('grade', sa.Text(), nullable=True),
    sa.Column('storage_type', sa.Text(), nullable=True),
    sa.Column('pack', sa.Text(), nullable=True),
    sa.Column('infomart_code', sa.String(length=6), nullable=True),
    sa.Column('spec_memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['infomart_code'], ['infomart_categories.infomart_code'], name='fk_product_specs_infomart'),
    sa.ForeignKeyConstraint(['tenant_id', 'product_id'], ['products.tenant_id', 'products.product_id'], name='fk_product_specs_product'),
    sa.PrimaryKeyConstraint('spec_id'),
    sa.UniqueConstraint('tenant_id', 'spec_id', name='uq_product_specs_tenant_id')
    )
    with op.batch_alter_table('product_specs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_specs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('company_plans',
    sa.Column('plan_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('spec_id', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.Text(), nullable=True),
    sa.Column('target_cost_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('planned_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume_kg_month', sa.Integer(), nullable=True),
    sa.Column('annual_volume_kg', sa.Integer(), nullable=True),
    sa.Column('max_acceptable_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'spec_id'], ['product_specs.tenant_id', 'product_specs.spec_id'], name='fk_company_plans_spec'),
    sa.PrimaryKeyConstraint('plan_id')
    )
    with op.batch_alter_table('company_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_plans_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('market_rates',
    sa.Column('rate_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('spec_id', sa.BigInteger(), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('price_yen_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('yoy_change', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('input_method', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'spec_id'], ['product_specs.tenant_id', 'product_specs.spec_id'], name='fk_market_rates_spec'),
    sa.PrimaryKeyConstraint('rate_id')
    )
    with op.batch_alter_table('market_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_rates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('negotiation_cases',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('case_no', sa.String(length=20), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('spec_id', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.Text(), nullable=True),
    sa.Column('case_type', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('proposed_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume_kg_month', sa.Integer(), nullable=True),
    sa.Column('annual_volume_kg', sa.Integer(), nullable=True),
    sa.Column('proposed_conditions', sa.Text(), nullable=True),
    sa.Column('claimed_reasons', sa.JSON(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('data_origin', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'spec_id'], ['product_specs.tenant_id', 'product_specs.spec_id'], name='fk_cases_spec'),
    sa.ForeignKeyConstraint(['tenant_id', 'supplier_id'], ['suppliers.tenant_id', 'suppliers.supplier_id'], name='fk_cases_supplier'),
    sa.PrimaryKeyConstraint('tenant_id', 'case_no')
    )
    with op.batch_alter_table('negotiation_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_negotiation_cases_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('negotiation_results',
    sa.Column('result_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('case_no', sa.String(length=20), nullable=False),
    sa.Column('result_date', sa.Date(), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delivery_term', sa.Text(), nullable=True),
    sa.Column('payment_site', sa.Text(), nullable=True),
    sa.Column('vs_quote', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vs_landing', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('achievement', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('result_tags', sa.JSON(), nullable=True),
    sa.Column('accepted_reasons', sa.JSON(), nullable=True),
    sa.Column('staff_memo', sa.Text(), nullable=True),
    sa.Column('handover_note', sa.Text(), nullable=True),
    sa.Column('prep_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('data_origin', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'case_no'], ['negotiation_cases.tenant_id', 'negotiation_cases.case_no'], name='fk_results_case'),
    sa.PrimaryKeyConstraint('result_id'),
    sa.UniqueConstraint('tenant_id', 'result_id', name='uq_negotiation_results_tenant_id')
    )
    with op.batch_alter_table('negotiation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_negotiation_results_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('strategy_sheets',
    sa.Column('sheet_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('case_no', sa.String(length=20), nullable=False),
    sa.Column('price_diff', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('annual_impact', sa.BigInteger(), nullable=True),
    sa.Column('calc_version', sa.String(length=20), nullable=True),
    sa.Column('target_auto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('target_final', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('landing_auto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('landing_final', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('walkaway_auto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('walkaway_final', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('line_edit_reason', sa.Text(), nullable=True),
    sa.Column('impact_target', sa.BigInteger(), nullable=True),
    sa.Column('impact_landing', sa.BigInteger(), nullable=True),
    sa.Column('impact_walkaway', sa.BigInteger(), nullable=True),
    sa.Column('ai_points', sa.Text(), nullable=True),
    sa.Column('ai_scenario', sa.Text(), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.Column('data_origin', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'case_no'], ['negotiation_cases.tenant_id', 'negotiation_cases.case_no'], name='fk_strategy_case'),
    sa.PrimaryKeyConstraint('sheet_id'),
    sa.UniqueConstraint('tenant_id', 'sheet_id', name='uq_strategy_sheets_tenant_id')
    )
    with op.batch_alter_table('strategy_sheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_sheets_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_sheets_tenant_id'))

    op.drop_table('strategy_sheets')
    with op.batch_alter_table('negotiation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_negotiation_results_tenant_id'))

    op.drop_table('negotiation_results')
    with op.batch_alter_table('negotiation_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_negotiation_cases_tenant_id'))

    op.drop_table('negotiation_cases')
    with op.batch_alter_table('market_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_rates_tenant_id'))

    op.drop_table('market_rates')
    with op.batch_alter_table('company_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_plans_tenant_id'))

    op.drop_table('company_plans')
    with op.batch_alter_table('product_specs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_specs_tenant_id'))

    op.drop_table('product_specs')
    op.drop_table('tenants')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_tenant_id'))

    op.drop_table('suppliers')
    with op.batch_alter_table('raw_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_imports_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_raw_imports_import_batch_id'))

    op.drop_table('raw_imports')
    op.drop_table('rate_change_reasons')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_tenant_id'))

    op.drop_table('products')
    op.drop_table('model_versions')
    op.drop_table('infomart_categories')
    # ### end Alembic commands ###
